### ISSUE TITLE
[FEATURE] Improve error surfacing

### ISSUE THREAD

**Issue by phestecAMZN** [opensearch-project/security-analytics-dashboards-plugin#117]
**Is your feature request related to a problem?**
Currently error toasts show for just about every operation/navigation, successful or not.

**What solution would you like?**
Need to alert user only when necessary.

**What alternatives have you considered?**
This is a necessity, as it interferes with user's actions as well as development

**Do you have any additional context?**

**Comment by jovancacvetkovic** [comment]
Two separate issues are created to fix be fixed: #205 and #206
This ticket can be closed.
