### ISSUE TITLE
[FEATURE] Add loading state for all tables/visualizations on Overview page

### ISSUE THREAD

**Issue by phestecAMZN** [opensearch-project/security-analytics-dashboards-plugin#118]
**Is your feature request related to a problem?**
It can take time for all to load, leading the user to conclude there is no content.  This feature will let user know content is in fact loading.

**What solution would you like?**
Add loading indication for the user to see

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by jovancacvetkovic** [comment]
Closed with PR #237
