### ISSUE TITLE
[FEATURE] Adjust styling for Finding details flyout

### ISSUE THREAD

**Issue by phestecAMZN** [opensearch-project/security-analytics-dashboards-plugin#121]
**Is your feature request related to a problem?**
This change would improve presentation of information by visually compartmentalizing it in a more clear way.

**What solution would you like?**
Adjust accordion style: - Add a top border to the first item- Put the accordion content in a grey container, see ISM’s policy detail page for sample: https://playground.opensearch.org/app/opensearch_index_management_dashboards#/policy-details?id=sample_policy

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by jovancacvetkovic** [comment]
@kamingleung are we going to add these changes to the flyouts? Also is there a way to have mocks or just use the link in a description? If we change these, should these be applied to rules and alerts too?

**Comment by kamingleung** [comment]
@jovancacvetkovic 
This applies to the Findings flyout's Rules detail section.
![image](https://user-images.githubusercontent.com/3692324/212414830-d0206e7b-cc94-4feb-b9c3-032bb9f4cef0.png)

**What solution would you like?**
Adjust the accordion for improving readability:
1) Add outlines for each accordion entry like [this](https://eui.elastic.co/v34.6.0/#/layout/accordion#styled-for-forms):
![image](https://user-images.githubusercontent.com/3692324/212413977-fb4e8df1-5345-4d5c-8c49-46cc564ce34c.png)
2) Add a background and padding to the content inside the accordion like this ([example from ISM](https://playground.opensearch.org/app/opensearch_index_management_dashboards#/policy-details?id=sample_policy)):
![image](https://user-images.githubusercontent.com/3692324/212414484-9ae33219-b3e7-4953-bfc5-55ab94b699d3.png)
