### ISSUE TITLE
[FEATURE] Get started | Add Alert info in the Get started pop-up

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#129]
**Is your feature request related to a problem?**
Alert info is missing in Get started popup

**What solution would you like?**
Add info about Alerts in the Get started popup
Step title: View security alerts
Description: 
After detectors are created, you can view alerts triggered by findings.
Buttons:  View alerts

**Do you have any additional context?**
Add alerts info as a third step, current Get started screenshot
![get started](https://user-images.githubusercontent.com/28289071/202434911-02becc2a-c616-44bb-9220-6238d45650b7.png)

Get started with Alerts info added.
![get started with alerts info](https://user-images.githubusercontent.com/28289071/203286063-961b183c-f19e-4a3e-a85f-16c8f07efd8d.png)

**Comment by kamingleung** [comment]
How about updating the Get Started text to the following?

Security analytics generates critical security insights from existing security event logs. [Learn more][eui-popout icon]
_(The learn more link should open a new tab to: https://opensearch.org/docs/latest/security-analytics/ )_

1. **Create security detector** Identify security findings and threats from your log datas with detection rules. Additionally, you can set up alerts based on rule conditions.
2. **Discover security findings** After detectors are created, you can view insights and analyze security findings.
3. **View security alerts** View alerts based on conditions you have specified from your detectors.
4. **Create custom rules for detectors** Create rule or fine tune existing rules that can be added to detectors. _(Step 4 should have two buttons - Create rule and Manage rules. Create rule should be a primary button)_

@jimishs Additional thoughts?

**Comment by jovancacvetkovic** [comment]
@kamingleung What about buttons for the first three steps? Leave them as they are?

**Comment by kamingleung** [comment]
@jovancacvetkovic 
Sorry, there's a typo in step 1, `log datas` should be `log data`

For buttons, the screenshot you provided looks good to me:
![Image](https://user-images.githubusercontent.com/3692324/203387747-f8c5ca18-e1b0-476a-98a2-b8492bc17ec9.png)

**Comment by jovancacvetkovic** [comment]
@kamingleung @amsiglan All reviews are resolved per this comment https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/129#issuecomment-1322627758

**Comment by jovancacvetkovic** [comment]
@kamingleung **datas** text updated to **data**

**Comment by jovancacvetkovic** [comment]
Resolved with PR #148
