### ISSUE TITLE
[FEATURE] Rules | Create/Edit detector | Source filter name

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#130]
**Is your feature request related to a problem?**
Still hasn't been decided what will filter be named. There are two options: Source and Library

**What solution would you like?**
Waiting on the designer's team to decide which label to use.

**Do you have any additional context?**
![source or library](https://user-images.githubusercontent.com/28289071/202448237-b67ed6e7-1a3a-4338-a252-93d8fd3665ae.png)

**Comment by amsiglan** [comment]
@jovancacvetkovic We should use "Source" label. So verify that is the case in all the places where we have a rules table and we can close this issue if no change is required.

**Comment by jovancacvetkovic** [comment]
> @jovancacvetkovic We should use "Source" label. So verify that is the case in all the places where we have a rules table and we can close this issue if no change is required.

@amsiglan I can confirm that there is no change required.

**Comment by jovancacvetkovic** [comment]
Nothing to do.
