### ISSUE TITLE
[FEATURE] Integration with the discover plugin

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/security-analytics-dashboards-plugin#132]
**Is your feature request related to a problem?**
Currently, the finding details flyout displays just the document which triggered the generation of the finding. It would be helpful to view the surrounding logs as well.

**What solution would you like?**
Integrate with the discover plugin to provide an intuitive UI experience for viewing logs adjacent to the log which generated a finding. This will require discussion with the security analytics, UX, and discover teams in order to answer the following questions, and determine how we would like to add this support.

1. We will need an index pattern for each index we want to display with this feature. That means each index/data source selected when defining a detector will need a corresponding index pattern. Backend create/update detector APIs would need to be refactored to create an index pattern for each index associated with the detector. Should creating index patterns automatically be optional? That may involve adding a new boolean field to the detector JSON payload.
2. Should we instead direct the user to the stack management -> index pattern creation UI, and then allow them to select which index patterns to associate with their detector? Unless the index pattern uses an * to match multiple indices, each index/data source associated with a detector will have to have its own index pattern (e.g., an * could not be used to match an index with the name `windows-index1` with another named `test-logs`; so each will need its own index pattern). We would then have to store the index pattern IDs in the detector JSON.
3. Do we need to provide a date/time field when creating the index pattern? It seems optional based on the index pattern creation UX, but need more clarity on what function it provides (date and time filters still seem available in discover when no date/time field is defined for the pattern). Would the user need to provide the desired field, or can we make any assumptions based on the log type? This might involve adding new fields to the detector JSON payload that would associate each index with a time field. Requiring the users to define the field may be necessary when detectors support multiple log types.

**What alternatives have you considered?**
This could be implemented, without discover integration, by performing a range query to retrieve and display the surrounding logs, but integrating with discover would allow us to leverage the built-in filtering and other functions of that plugin.

**Do you have any additional context?**
The UI mocks have a draft of what this would look like.

**Comment by kamingleung** [comment]
**Idea 1** 
Check if an index pattern has been created when a user clicks on "View surrounding documents". 
- If there is an index pattern exist, it will open a new tab into Discover. 
- If there are no index pattern for that index, it will show a modal to prompt user to create the index pattern. Once index pattern has been created, users can then "View surrounding documents" in Discover. Here's a quick mockup to show the above interaction:
![image](https://user-images.githubusercontent.com/3692324/203203657-2e3d071d-9cb0-46d2-937b-6e9faca7547d.png)

**Idea 2**
I am still wondering if we can make this a seamless experience by automating this? The above flow requires users to take additional steps just to be able to view and explore logs in Discover. Would users need to do this for every index? Perhaps can we automate this when a detector is created/edited?
Does this approach align with best practices?

**Comment by AWSHurneyt** [comment]
@kamingleung 
> Idea 1
Check if an index pattern has been created when a user clicks on "View surrounding documents".
> 
> If there is an index pattern exist, it will open a new tab into Discover.
If there are no index pattern for that index, it will show a modal to prompt user to create the index pattern. Once index pattern has been created, users can then "View surrounding documents" in Discover. Here's a quick mockup to show the above interaction:

To check whether the index pattern exists, I believe we'd have to decide whether we want that to mean the index pattern `title` is exactly the same as the index name/data source provided when configuring the detector. For example, if a user has index patterns with the titles `window*` and `windows`, and they configure a detector with a data source called `windows`, do we want **both** of those index patterns to be considered potential matches for our purposes? What if that same user instead only had a single index pattern with the title `window*`. Do we want to prompt that user to create an index pattern for the data source `windows`, or assume we can use the existing one?

I'm of the mindset that we should look for **exact** matches (e.g., `windows` `===` `windows`, but `window*` `!==` `windows`) because an index pattern titled `window*` could be associated with numerous data sources (e.g., `window-installations`, `window-buyers`, `windows-logs`) that may not relate to what they store in the `windows` data source they configured in their detector. Similarly, if a user had an index pattern titled `windows`, but configured their detector with a data source called `window*`, the discover page displayed for the `windows` index pattern might not contain all of the document results the user expects.

QUESTION: If the existing index pattern creation UX isn't readily available for reuse, should we attempt to recreate those assets, or would it be better to instead redirect them to the stack management UX with a helpful prompt (e.g., `To view surrounding logs, create an index pattern with the title "<DATA_SOURCE_NAME>"`). The later seems safer in my opinion, as it would mean we're not maintaining index pattern-creation assets that may eventually diverge from the experience on the stack management page.

> Idea 2
I am wondering if we can make this a seamless experience by automating this? The above flow requires users to take additional steps just to be able to view and explore logs in Discover. Would users need to do this for every index? Perhaps can we automate this when a detector is created/edited?
Does this approach align with best practices?

Yes, my understanding is that users would have to create an index pattern for each data source configured in a detector. We could automate that process by refactoring the create/update detector APIs to create an index pattern for each data source in the detector JSON payload, but there are a few points to consider:
1. In order to create an index pattern, the user must have dashboards installed and running. The create saved object API is made against the dashboards host (e.g., `localhost:5601`), not the core host (e.g., `localhost:9200`). If we decide to automate the process, we may need to implement a listener on the backed that detects when dashboards is running, then iterate through each of detectors and creates index patterns for any data sources which don't have one. This would control for situations when the user created detectors before installing dashboards, or while dashboards was down.
2. As discussed during our internal sync yesterday, it sounds like we cannot assume which time field, if any, should be used for an index pattern based solely on the log type associated with the detector (especially if support for multiple log types per detector is implemented); and the time field cannot be changed once the index pattern is created. As a result, we could not automate the process of creating an index pattern with a time field; all of the index patterns we automatically create would not be able to make use of the global time filters on the discover page. 

As mentioned above, in my opinion, it would make sense to prompt the user to create the index pattern rather than create it for them. This would allow them to configure a time field if desired.
___

**Misc. notes**

Regarding creating index patterns on behalf of users, we can supply a custom index patten ID when calling the creation API. An example request is below. We could potentially use this functionality to always know the index pattern ID (which is needed to display the discover page for a data source) if we decide to automatically create the index patterns.
```
curl -X POST "localhost:5601/api/saved_objects/index-pattern/CUSTOM_ID -H 'osd-xsrf: true' -H 'Content-Type: application/json' -d '
{
  "attributes": {
    "title": "DATA_SOURCE_NAME"
  }
}'
```
We could use the following command to check whether the index pattern exists.
```
localhost:5601/pxj/api/saved_objects/_find?type=index-pattern&search_fields=title&search=DATA_SOURCE_NAME

**Comment by AWSHurneyt** [comment]
A point of consideration. Users will be able to delete any index patterns we create for them through the `stack management` UI, but we could add a check in the index pattern creation modal to confirm the pattern exists, and prompt them to create it if it doesn't.

**Comment by djindjic** [comment]
@kamingleung @AWSHurneyt @amsiglan 

Here is my implementation on idea 1 flow, please take a look:

https://user-images.githubusercontent.com/1564068/213536149-e1b70d5c-79f6-42d2-b0ee-bdfc42400427.mov

**Comment by kamingleung** [comment]
@djindjic Thanks for your update.
@AWSHurneyt @amsiglan Were we able to automate the index pattern creation (idea 2)?

**Comment by amsiglan** [comment]
@kamingleung We took the route of showing the modal to create an index pattern if one is not available already.
