### ISSUE TITLE
[FEATURE] Disable notification option for alerts if alerting plugin is not present

### ISSUE THREAD

**Issue by djindjic** [opensearch-project/security-analytics-dashboards-plugin#134]
**Is your feature request related to a problem?**
Creating notification alert option is visible in following flows even if there is no alerting plugin installed.
- [x] Create detector flow
- [x] Edit detector - alert triggers
- [x] Create Alert on Findings

**Do you have any additional context?**
Follow what the alerting plugin does

**Comment by AWSHurneyt** [comment]
As mentioned in [this comment](https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/136#discussion_r1028583029) on PR #136, we should ideally have different disable logic for notification components based on whether the notifications front or backend plugin is required. 

As mentioned in that comment thread, PR #136 isn't blocked by this, but let's leave this issue open as a follow-up item.
