### ISSUE TITLE
[BUG] No URL provided on "Learn more" link

### ISSUE THREAD

**Issue by djindjic** [opensearch-project/security-analytics-dashboards-plugin#137]
**What is the bug?**
Missing linked url in user notification.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1564068/202796720-63452aff-fbf1-4918-aafd-94d2dbca9bde.png">

**How can one reproduce the bug?**
1. Go to findings page
2. Click on create alert icon button of any finding
3. Check "Alert and notify" section in Flyout panel

**What is the expected behavior?**
Learn more link should open right page in new tab

**Comment by kamingleung** [comment]
We can set the link to point to the notifications plugin documentation: https://opensearch.org/docs/latest/notifications-plugin/index/
