### ISSUE TITLE
[FEATURE] Implement Dashboards page

### ISSUE THREAD

**Issue by paladin-tech** [opensearch-project/security-analytics-dashboards-plugin#14]
**Is your feature request related to a problem?**
Similar to the dashboards available under the [SIEM on opensearch](https://github.com/aws-samples/siem-on-amazon-opensearch-service/blob/main/docs/dashboard.md) project, we want users to be able to visualize the data for the log types supported by Security analytics using out of box dashboards tailored to each log type.

**What solution would you like?**
A couple of possibilities:
1. A separate Dashboards page where users get a create/setup dashboard UI. As part of it, users select the log type and log source. Based on that info, SA would create the dashboard and open the dashboard using the Dashboard plugin
2. While creating the detector, users check a create dashboard checkbox and we create the dashboard for them behind the scenes which will be available under the Dashboards list and also on the Detector details page.

**Comment by amsiglan** [comment]
We added support for pre-canned dashboards as part of detector creation
