### ISSUE TITLE
[FEATURE] Add hover info text for detector "Active" or "Disabled" status 

### ISSUE THREAD

**Issue by paladin-tech** [opensearch-project/security-analytics-dashboards-plugin#143]
**Is your feature request related to a problem?**
Detector status (Active/Inactive) on Detector Details page is marked in red text color.
![image](https://user-images.githubusercontent.com/3697900/202538440-ab58f9f8-8cf1-4cce-8e0b-f2bfe75ad410.png)
This should be accompanied with hover information.

**What solution would you like?**
Adding a Tooltip around the Detector status label. Is this what is expected? @amsiglan @kmleung
Also, what is the expected text?

**What alternatives have you considered?**
Is there some special behavior, similar to autotrigger using EuiTour?

**Do you have any additional context?**
-

**Comment by amsiglan** [comment]
@kamingleung  There are no intermediate states, but while the status is being adjusted, it can take a couple of seconds. While we work on improving the perf, do we want to show some loading indicator here?
