### ISSUE TITLE
[BUG] Edit detector | Edit Field mappings | Field mapping is wrong

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#144]
**What is the bug?**
Editing field mappings resets mapping to defaults, instead, it should use already mapped values.

**How can one reproduce the bug?**
1. Go to the Detectors page and click on any detector from the list
2. Go to the Field Mappings tab
3. Notice that, in view, all fields are mapped correctly
4. Click on the Edit button
5. Notice that field mapping is wrong

**What is the expected behavior?**
Editing Field Mapping should use already set mapping values

**Do you have any screenshots?**
Correct mapping in the view
![correct_field_mapping](https://user-images.githubusercontent.com/28289071/202841818-e223d0b2-5c85-4a7c-83fe-5581047eef7d.png)

Incorrect mapping in editing mode
![incorrect field mapping](https://user-images.githubusercontent.com/28289071/202841827-832c326c-91d0-42a8-ace6-7bb68d44b1f5.png)

**Comment by canob** [comment]
Adding some problems to these:
- I created a Detector and configured Field Mappings.
- When I review the Field Mappings in the created Detector, it shows empty:
![imagen](https://user-images.githubusercontent.com/30271927/205629689-a82b0145-94c0-451a-b73e-4d1e28770f0f.png)
- But when I edit it, it shows normally, with the fields that I already mapped:
![imagen](https://user-images.githubusercontent.com/30271927/205629872-c6ad0cfd-0a6d-4f3f-92ef-53ed1da1b02f.png)
