### ISSUE TITLE
[FEATURE] Create/edit rule in YAML format

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/security-analytics-dashboards-plugin#154]
**Is your feature request related to a problem?**
As a user, I should be able to create/edit a rule in YAML format or with a guided visual editor.

**What solution would you like?**
- In the Create rule flow, users have the option to define a rule using visual or YAML editor with a toggle.
- Users can toggle between editor and the rule will be translated. For example, if a user started creating the rule in YAML, then toggles over to visual editor, everything from the YAML editor will be translated into the visual editor. The user can continue editing the rule in visual editor.

**What alternatives have you considered?**
Open to suggestions!

**Mockups**
1. In the create rule flow, users can click on "YAML editor" to switch from Visual editor to YAML editor. (For toggle, use the [EuiButtonGroups](https://eui.elastic.co/v34.6.0/#/navigation/button#button-groups) component with "single" type)
![image](https://user-images.githubusercontent.com/3692324/203212426-31944aaa-c706-4ecd-9cdf-814d450d7ed0.png)

2. Here's how it looks like when toggled to YAML editor. Users can click on "Visual editor" to return the define the rule using the UI. (The "Sigma specification" link should point to: https://github.com/SigmaHQ/sigma-specification)
![image](https://user-images.githubusercontent.com/3692324/204391519-bea72ef7-9ada-46e4-ae5e-b5bde88e447b.png)
[Updated screenshot] Added label and description text for the YAML editor: 
Label: Define rule in YAML
Description text: Use the YAML editor to define a sigma rule. See [Sigma specification](https://eui.elastic.co/v34.6.0/#/navigation/button#button-groups) for rule structure and schema.

**Comment by kamingleung** [comment]
@djindjic I have updated the second screenshot above with new text for labels and description text.

**Comment by kamingleung** [comment]
@djindjic 
1. The `Rule name` and `Title` are referring to the same fields. Can these be 2-way binded?
2. We can add a `Date` field on the visual editor. For the `Modified` field, I assume this will be auto-generated?
3. I believe `Log type` is a new field we are introducing and to be categorized with the detector, should we add this as a required field in the rule schema? I don't think we are leveraging the `logsource`. @getsaurabh02 @sbcd90, can you provide some insights on how we will handle this?

If we are able to resolve the above 3 issues, what else is preventing this from allowing users to switch between visual and YAML editors?

**Comment by djindjic** [comment]
@kamingleung @amsiglan 
I have managed to handle "2-way-binding" fully aligned with original idea in the Mockup. Base on original YAML file (also visible in mockup) there are few open question some. Some of them are already mentioned:

  - date and modified not existing in visual editor (we can think of it and create new issue for adding date pickers) - currently ignoring @kamingleung 
  - `logsource` yaml property is an object that should have some special mapping based on my sync with backend devs. Currently mapping `logsource.product` to `Log type` dropdown (`category` key on Rule interface), but we just need to confirm it with someone more involved @amsiglan 
  - `log_source` key on `Rule` interface seem like not in use @amsiglan
      <img width="327" alt="image" src="https://user-images.githubusercontent.com/1564068/206002703-9b938f9a-4d10-4ca4-b9de-8491aa956e85.png">
  - tags validation (synced with @petardz, we should always have tags in format `namespace.name`. This is missing validation on Visual Editor too at the moment @amsiglan 
  - yaml validation messages - I don't have full list of possible invalid cases and edge cases at the moment, that part of my next research

Will keep you posted here.

**Comment by kamingleung** [comment]
@djindjic Thanks for your update! In the video, I noticed the rule name has some naming restrictions. What are the restrictions? Can we provide an inline validation for the visual editor and return an appreciate error message when trying to submit on YAML editor? "Enter valid input for Rule name" is a bit unclear for users.

**Comment by djindjic** [comment]
@kamingleung good catch, thanks. Since I've already started on next task, I've created 2 new issues based on your finding: https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/214 and https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/215. Also added to our internal tracking tool.

@amsiglan @kamingleung Please let me know if https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/215 is enough high priority for v2.5

**Comment by djindjic** [comment]
@amsiglan since https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/201 is merged and I created follow-up tasks, my suggestion would be to close this issue to reflect on the project board, or let me know to merge these follow-ups together here eventually.
