### ISSUE TITLE
[FEATURE] Overview | Update stats to use EUI stats component

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#156]
**Is your feature request related to a problem?**
Update stats to use the EUI stats component 

**Do you have any additional context?**
Current stats screenshot
![stats](https://user-images.githubusercontent.com/28289071/203335084-f44ba843-1a08-4fa8-b134-9af29dabed11.png)

Updated stats component
![stats updated](https://user-images.githubusercontent.com/28289071/203335145-00c75577-c2ac-4431-a6e2-a6ae02cf067a.png)
![updated stats component](https://user-images.githubusercontent.com/28289071/204465142-7399f8d6-019f-4325-948d-142c7622ea1f.png)
![stats loading](https://user-images.githubusercontent.com/28289071/204773134-7b47d260-ef64-49f5-8ec8-813ec62db489.png)

**Comment by jovancacvetkovic** [comment]
@amsiglan @kamingleung Overview stat's component is updated, the stats look slightly different. Can you guys confirm if this is ok to go with? Also, there is a loading animation while the request for data is not yet done, the last screenshot. Stats are clickable and will take the user to the dashboards.

**Comment by kamingleung** [comment]
@jovancacvetkovic That looks fine to me. If a user clicks on the number of total active alerts, it should go to the Alerts page. If clicking on the number of total findings, it should go to the Findings page.

**Comment by jovancacvetkovic** [comment]
> @jovancacvetkovic That looks fine to me. If a user clicks on the number of total active alerts, it should go to the Alerts page. If clicking on the number of total findings, it should go to the Findings page.

@kamingleung that is correct, moving on with this ticket.
