### ISSUE TITLE
[FEATURE] Run integration tests as part of the OpenSearch-Dashboards distribution

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/security-analytics-dashboards-plugin#17]
**Is your feature request related to a problem?**
Following a problem in another plugin (https://github.com/opensearch-project/opensearch-build/issues/2043), and coming from https://github.com/opensearch-project/opensearch-build/issues/58, there's no automated testing that this plugin runs as part of the OpenSearch distribution.

**What solution would you like?**
Run integration tests as part of the distribution.

A bit different from the OpenSearch Gradle IntegTest, the cypress test on dashboards need to be added to https://github.com/opensearch-project/opensearch-dashboards-functional-test

**Comment by AWSHurneyt** [comment]
Onboarded to 2.4 https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/380
PR drafted to onboard to 3.0, but the security analytics front and backend plugins do not currently have a 3.0 dev branch https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/382
