### ISSUE TITLE
[FEATURE] Add chart tooltips

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#198]
**Is your feature request related to a problem?**
Add chart tooltips for a better user experience. Tooltips are already implemented on the Discover page.

**Do you have any additional context?**
![tooltip](https://user-images.githubusercontent.com/28289071/205721953-96724d39-d530-4715-94fd-b20625700703.png)

As these above are outdated, the next screenshot shows the default vega-lite tooltip
![FEATURE  Add chart tooltips #198](https://user-images.githubusercontent.com/28289071/207706002-47a68b80-7433-4ef7-9eb4-c7b5d56f9e95.png)

**Comment by jovancacvetkovic** [comment]
@amsiglan @kamingleung what do you think, is it ok to go with the default tooltip?

**Comment by jovancacvetkovic** [comment]
Closed with PR #225

**Comment by kamingleung** [comment]
@jovancacvetkovic Sorry for a late respond, are we using the tooltip component provided by Vega-lite? https://vega.github.io/vega-lite/docs/tooltip.html
Let's style the tooltip to match the ElasticCharts style along showing the color of the trend line the data is on. For graphs with multiple datasets like your screenshots, it should show all of the data set in the same tooltip, see [this page](https://eui.elastic.co/v34.6.0/#/elastic-charts/creating-charts) for a demo. 

Also a screenshot reference on ElasticCharts:
![image](https://user-images.githubusercontent.com/3692324/208983835-b18d5f57-7c85-47ef-a5b5-a2f8388da3dc.png)

**Comment by jovancacvetkovic** [comment]
@kamingleung Yes, we are using the default tooltip from Vega-lite, current version of vega-tooltips we are using doesn't support customizing the tooltips. I created an issue [#254](https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/254) to check if we can safely update the vega-tooltips version.
