### ISSUE TITLE
[BUG] Create/Edit Rule - Visual Editor - Client side validation on tag format

### ISSUE THREAD

**Issue by djindjic** [opensearch-project/security-analytics-dashboards-plugin#207]
**What is the bug?**
Format should be validated on frontend side to respect sigma rule spec: https://github.com/SigmaHQ/sigma-specification/blob/main/wip/Sigma_2_0_0.md#tags
and backend should not fail on tag "with no dot" in name.
```
- Character set: lower-case letters, underscores and hyphens
- no spaces
```
@amsiglan Sync with backend guys if dot is not required since namespace can be just one word without "sub space". In that case (java) backend should not throw an error.

**How can one reproduce the bug?**
1. create new rule with single word tag

**Comment by amsiglan** [comment]
@sbcd90 can you look into the tag requirement? If SIGMA rule can have one word tag then we shouldn't mandate it in security analytics

**Comment by djindjic** [comment]
@amsiglan @getsaurabh02 @mingshl 

simplified version as we agreed is fixed in context of PR https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/279

please check the video:

https://user-images.githubusercontent.com/1564068/210131276-4c46d4df-2172-4bff-a243-538285e5d064.mov
