### ISSUE TITLE
[BUG] Clicking on a rule should open a flyout in Create detector

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/security-analytics-dashboards-plugin#212]
**What is the bug?**
in the Create detector flow, when a user clicks on a rule in Step 1, it should open a flyout with the rule details. This flyout should contain the same rule information and as the rule flyout in the Rule editor.

**How can one reproduce the bug?**
1. Go to 'Create detector'
2. On Step 1: Define detector, open "Detection rules"
3. Click on any rule links
4. The links are currently not doing anything

**What is the expected behavior?**
When a user clicks on a rule link, it should open a flyout on the same page. The flyout should contain the rule details.

**Do you have any mockups?**
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/3692324/207135944-aff601dd-3ae1-4964-b748-755069e5a664.png">

**Comment by djindjic** [comment]
@kamingleung here is how it looks in my local at the moment while its in peer review

https://user-images.githubusercontent.com/1564068/208235024-37ee1577-a4f8-40a0-a375-807b16618f89.mov

**Comment by kamingleung** [comment]
@djindjic Follow-up question: On step 4 of the create flow, does clicking a rule name also open a flyout with rule details? If not, we can create a new issue for that.

![image](https://user-images.githubusercontent.com/3692324/208982473-87e0aff3-5bcb-4423-9738-f25ffc583818.png)

**Comment by djindjicdev22** [comment]
Good point @kamingleung, it doesn't open flyout on page 4.
Also it could be added to edit detector page?

**Comment by djindjic** [comment]
Good point @kamingleung, it doesn't open flyout on page 4.
Also it could be added to edit detector page?
