### ISSUE TITLE
[FEATURE] Create/Edit rule validation on submit and visual-yaml editor switching

### ISSUE THREAD

**Issue by djindjic** [opensearch-project/security-analytics-dashboards-plugin#215]
**Is your feature request related to a problem?**
Specific client side validations should be shown inlined on form submit (not only on blur) for both visual and yaml editor.
Additionally, show client side validation messages while switching between editors.

https://user-images.githubusercontent.com/1564068/207249977-5e9a2868-15bf-435b-96f6-8f059573cbad.mov

**Comment by djindjic** [comment]
@kaming @getsaurabh02 

We should have same form validation experience as we have on other plugins. Here is an example of `Create rollup job` form on `Snapshot Management` plugin.

https://user-images.githubusercontent.com/1564068/209216499-fc901b2c-6da3-4561-9a2b-4cfbb7fd548b.mov

Please notice that even this form is not fully consistent since required message on job name is different depending if user action is clicking submit button vs blur out of input field.

**Acceptance Criteria** should be:
- form has no red flags on initial state
- touching the field (blur out) triggering validation on that field and shows eventual inline error message
- clicking submit button (create or edit in case of rule forms) triggers all validations on all fields and shows all eventual error messages
- generally speaking, server side validation error messages or some unhandled errors should be shown in form of toast notification

I still need to think on switching the editor type behavior in context of validation messages

**Comment by kamingleung** [comment]
@djindjic Do we know which fields are required to create a rule? 
I am assuming we need the following with requirements:
- Rule name
- Log type
- Detection
- Rule level
- Author
- Rule status

Here are some guidance on validation pattern:
If any of the required fields are empty, we can show validation error onBlur until the issue is fixed, [fieldName] is required.
Like this:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/3692324/209237722-4203874d-2343-46c8-8a12-1c6eb536a322.png">

If users attempt to click on Create when there are validation errors, we should show a toast like this:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/3692324/209237702-7cef809c-1dd7-4612-9bfe-5e9d430ad6a0.png">

**Comment by kamingleung** [comment]
For dropdowns in this create flow, we should leave them empty by default, with a placeholder text:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/3692324/209239947-070ee5ac-d696-441e-a541-52e31cabc482.png">

When users click on the dropdown, they will select from the selections.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/3692324/209240050-585619f2-53a9-499f-a95f-c92cae1eb3b5.png">

If the user didn't select anything when clicking on Create, it will show the toast above and inline validation error:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/3692324/209240359-a9ecb079-016a-446b-ba26-4d51d2a654ef.png">

**Comment by kamingleung** [comment]
I assume the following fields are optional?
- Description
- Tags
- References
- False positive cases

Let's add "_- optional_" in italics to help users identify which fields are required. Like this:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/3692324/209241095-fd66a2b2-a227-4885-a7bf-0de0c0929e51.png">
Example from Create rollup job in Index Management.

**Comment by djindjic** [comment]
> If users attempt to click on Create when there are validation errors, we should show a toast like this at the bottom right of the screen: <img alt="image" width="344" src="https://user-images.githubusercontent.com/3692324/209237702-7cef809c-1dd7-4612-9bfe-5e9d430ad6a0.png">

@kamingleung 
At the moment I have the only one issue with show toaster if form is already invalid (for submission is blocked). Let me know if I can find this example on playground? I guess this toaster is produces by some backend error or validation outside of the form itself.

**Comment by djindjic** [comment]
> I assume the following fields are optional?
> 
> * Description
> * Tags
> * References
> * False positive cases
> 
> Let's add "_- optional_" in italics to help users identify which fields are required. Like this: <img alt="image" width="421" src="https://user-images.githubusercontent.com/3692324/209241095-fd66a2b2-a227-4885-a7bf-0de0c0929e51.png"> Example from Create rollup job in Index Management.

@kamingleung 
This is possible with custom flex group above the form field. Check how it is done in index management:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/1564068/209507445-5a447966-e52c-4793-81a3-2f2efc323545.png">
But I would try to go with some of form layout features defined in docs:
https://eui.elastic.co/v34.6.0/#/forms/form-layouts
Unfortunately, can't find some special flags for required/optional, but maybe help text below the field could be also used?

**Comment by djindjic** [comment]
@kamingleung @amsiglan @getsaurabh02 
I've covered all necessary behaviors except this two:
1. `- optional` sufix is not gray-italic for now because of no clear directions on https://eui.elastic.co/v34.6.0/#/forms/form-layouts and I wanted to avoid custom layouting of that purpose (still open for discussion about custom layouting)
2. Action buttons (Cancel, Create/Save changes) are now in the `<ContentPanel>` together with the form. This is still possible to be outside as it was before, but I've decided to put it on hold since its not "one line fix" and we have few more prio tasks at the moment.

Please check current behavior on the video and compare it to old behavior on [playground](https://playground.opensearch.org/app/opensearch_security_analytics_dashboards#/create-rule)


https://user-images.githubusercontent.com/1564068/209636858-ed613da5-7db2-491a-9165-26cf8fff5cd0.mov

**Comment by kamingleung** [comment]
@djindjic Thanks for your updates. 
1. The `- optional` isn't a reusable style/component in EUI today, however we can align the style of `- optional` found in the Create detector flow.
2. Action buttons - Let's place them underneath the container to align with the placement with other create flows in Dashboards

Follow-up questions from your video:
3.  Are these confirmed as naming restrictions on Rule name and author? 
![image](https://user-images.githubusercontent.com/3692324/210026331-0c2da0e3-5e94-480c-bfbb-3bfefe1d5db3.png)

We should show restriction text underneath the form field at all times like this (example from Anomaly Detection):
![image](https://user-images.githubusercontent.com/3692324/210026503-ff8f4b8b-b2d9-4569-aab4-a2508b8fd808.png)
When, there are invalid naming requirements, we can show error above the restriction text, "Invalid rule name" like this:

**Comment by djindjic** [comment]
@kamingleung
I think I've addressed all you points except:
1. extended author restriction text with commas (reflecting existing validation in the code)
2. added similar restriction text underneath description field based on existing validation in the code (including commas and dots)

Since PR for this issue is already merged I've done it in currently active one which is related (https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/279)

Please check video:

https://user-images.githubusercontent.com/1564068/210109993-25a49a70-ff50-4769-acd3-8bd68d47568e.mov

**Comment by kamingleung** [comment]
@djindjic This looks good to me. Thanks for your updates!
