### ISSUE TITLE
[FEATURE] Upgrade Vega-tooltips plugin version

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#254]
**Is your feature request related to a problem?**
The current version of the vega-tooltip package is 0.24.2 and doesn't support customizing the vega-tooltip.

**What solution would you like?**
Update the vega-tooltip version to 0.30.0 which does support customizing via formatTooltip API
https://github.com/vega/vega-tooltip/blob/next/docs/APIs.md#options

**Comment by amsiglan** [comment]
The update was made in the OSD - https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3432
