### ISSUE TITLE
[FEATURE] Add Windows Support 

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/security-analytics-dashboards-plugin#33]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [x] Passing CI on Windows
- [x] Documentation

**Comment by dblock** [comment]
I believe integration/cypress tests aren't running on Windows as part of this, reopening. Please close when there's no gap in testing across platforms, or if something cannot be done, please open a separate issue for it for tracking.

**Comment by peterzhuamazon** [comment]
Hi, just want to make sure this issue is closed, if all the tasks are completed.

Thanks.

**Comment by amsiglan** [comment]
Cypress tests running on windows
