### ISSUE TITLE
[FEATURE] Trigger name should be required in Create alert trigger flyout

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/security-analytics-dashboards-plugin#352]
**Is your feature request related to a problem?**
When creating a detector alert trigger from the findings page, if a user didn't enter a required field (e.g. Trigger Name), clicking on "Create alert trigger" will let users proceed to create. Trigger name should be required just like in the Create detector flow. Without a trigger name, it is difficult to identify what the alert is about.

**What solution would you like?**
1. Users go to "Findings" page, click on the bell icon of a finding to open the Create alert trigger flyout.
![image](https://user-images.githubusercontent.com/3692324/211901582-68ea1ea3-4ff5-4a43-beb6-5abc96a7408b.png)
2. When users open the flyout, the Trigger name field should be focused to guide users to fill in a name:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/3692324/211894615-b4bf89be-2ede-4090-902b-94a10298ce66.png">
3. On blur, we should display a validation error if the trigger name is left empty. `Trigger name is required.`:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/3692324/211894783-31069ad1-becb-40eb-9103-6e0b830ab7fb.png">
4. If required fields are not filled in, we should keep the Create button disabled:

![image](https://user-images.githubusercontent.com/3692324/211899065-ee890b33-3572-42aa-a884-cc216c06ce2c.png)

**Comment by jovancacvetkovic** [comment]
@kamingleung, @amsiglan I noticed that users can create alerts from a flyout without a rule or severity. Creating a detector also allows these fields to be empty. 
Is this OK behavior?

**Comment by kamingleung** [comment]
@jovancacvetkovic The Rule and Severity fields can be empty. If these two fields are empty, it means it will include any rules and any severities:
![image](https://user-images.githubusercontent.com/3692324/213269389-867ca77f-8b01-4806-a03f-9dd9d922e751.png)
