### ISSUE TITLE
[FEATURE] Create detector | Make data source multi-select field

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#419]
**Is your feature request related to a problem?**
A user should be able to select multiple indexes (or index/alias patterns) while creating the detector. 
**Note:** All indexes should have the same field mappings.

**What solution would you like?**
In the create detector flow, add a multi-select field that users can use and select one or more indexes.
If the user selects indexes with different field mapping, a banner message should be visible notifying the user that there are indexes with different field mappings.

**Additional**
Added a tooltip for the field mappings table, status column now has a tooltip hovering over the status icons.
![image-4e5b78f1-bfcc-4c9a-b796-0caea84d3f96](https://user-images.githubusercontent.com/28289071/220336540-15181865-7370-431e-93aa-f471cb05af32.jpg)

**Error message:**
Detector configuration warning
The below log sources don't have the same fields, please consider creating separate detectors for them.

![Screenshot from 2023-02-21 12-18-30](https://user-images.githubusercontent.com/28289071/220332333-5e407b4b-9f2b-4b42-86e9-b4b68fe52965.png)

**Comment by amsiglan** [comment]
For the error message, I think we should indicate that the indices are for different log types and should only belong to the <selected-logType> type.

**Comment by kamingleung** [comment]
@jovancacvetkovic 
- When does this banner show up? What are the checks are we doing in the background?
- Does it check all the indexes to make sure they have the same fields **before** users select a log type?

> Error message:
> Detector configuration warning
> The below log sources don't have the same fields, please consider creating separate detectors for them.

**Comment by jovancacvetkovic** [comment]
@kamingleung If the user selects two or more indexes with different log types, their fields will not match, then the banner shows up. Whenever the user selects an index the validation will trigger. Note that this is not a blocking operation, just a warning.
