### ISSUE TITLE
[FEATURE] Provide empty states for Overview page

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/security-analytics-dashboards-plugin#464]
**Is your feature request related to a problem?**
**Issues today:** On the overview page, there are no clear messages or guidance on what to do when there are no findings and alerts found within the time range. 
Current behavior:
1) It shows a blank chart 
2) The count of `Total active alerts` and `Total findings` are in loading state (they kept on blinking)
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/3692324/221675868-829d8a00-6dc0-4f40-965c-39e09dd27ef9.png">

**What solution would you like?**
Once the UI had finished fetching the data, and if there are no alerts AND no findings, we should replace the chart with an empty prompt:
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/3692324/222540268-c7c6ac87-537f-47b6-b618-21026b423122.png">
- Header: No alerts and findings ~found~
- Description: Adjust the time range to see more results or create a detector to generate findings.
- Clicking on the link `create a detector` will go to the Create detector page
- Use [OUI empty prompt component](https://eui.elastic.co/v34.6.0/#/display/empty-prompt)

Once the UI had finished fetching the data with no alerts or no findings, we should show 0 for `Total alerts trigger` or `Total findings` respectively:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/3692324/221680243-506bd4d9-2c3b-4051-8424-a04d26b5bf6c.png">
- Use [OUI stat component](https://eui.elastic.co/v34.6.0/#/display/stat) with subdued color when the count is 0.
- It won't be a link if the value is 0.

We will also need to update the other empty states on the Overview page with similar messaging:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/3692324/222542544-a78d9c9a-e0a9-44bb-a44f-2e7b4b19e38b.png">

Most frequent detection rules:
`No findings with detection rules.
Adjust the time range to see more results.`

Recent alerts:
`No recent alerts.
Adjust the time range to see more results.`

Recent findings:
`No recent findings.
Adjust the time range to see more results.`

**Comment by amsiglan** [comment]
@kamingleung Should those counts still be links to the Alerts/Findings pages or should they be disabled?

**Comment by amsiglan** [comment]
@kamingleung Should we have similar empty prompts in the Findings and Alerts pages as well?

**Comment by amsiglan** [comment]
@kamingleung We also need some text for the most frequent rules widget when it is empty 
![image](https://user-images.githubusercontent.com/114732919/222312697-5d03394e-2338-4d79-83a3-5be7427bc489.png)

**Comment by kamingleung** [comment]
@amsiglan
> Should those counts still be links to the Alerts/Findings pages or should they be disabled?

^ Yes, they won't be clickable when the value is 0.

> We also need some text for the most frequent rules widget when it is empty

^ The empty state text would be 
`No findings with detection rules.
Adjust the time range to see more results.`
<img width="652" alt="image" src="https://user-images.githubusercontent.com/3692324/222541587-3aee3f3c-8dff-4d9d-9965-00a5a5716efd.png">

We will also need to update the other empty states on the Overview page with similar messaging:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/3692324/222542544-a78d9c9a-e0a9-44bb-a44f-2e7b4b19e38b.png">

Recent alerts:
`No recent alerts.
Adjust the time range to see more results.`

Recent findings:
`No recent findings.
Adjust the time range to see more results.`

**Comment by kamingleung** [comment]
@amsiglan 

> Should we have similar empty prompts in the Findings and Alerts pages as well?

A separate issue was created for these two pages: https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/471
