### ISSUE TITLE
[BUG] During the detector creation, the automatically mapped fields count is 0

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#488]
**What is the bug?**
During the detector creation, the automatically mapped fields count is 0 and there are no pending filed mappings.

**How can one reproduce the bug?**
1. Create a rule with a new field or misspelled field.
2. Go to the detectors page and click on create detector button
3. Fill in all the fields and in the rule's table select only the newly created rule.
4. Click on the Next button
5. Check out the message - this message is misleading saying all fields are mapped when this is not correct. In this case, there are no fields to map, and query fields from the rule did not match any log fields.

**What is the expected behavior?**
Perhaps a message to notify the user there are no fields found that match the query fields for the selected rule? 

**Do you have any screenshots?**
![Screenshot from 2023-03-17 11-54-17](https://user-images.githubusercontent.com/28289071/225885790-b31f77bb-9419-421a-a625-d6f0090c466e.png)

**Comment by jovancacvetkovic** [comment]
@amsiglan @kamingleung Hey guys, if you think this is a valid issue let's make a new message.

**Comment by getsaurabh02** [comment]
Needs more investigation on the mapping API in the backend. 
cc : @sbcd90 @petardz

**Comment by amsiglan** [comment]
Fixed
