### ISSUE TITLE
[BUG] Tracking issue for flaky and failing cypress tests

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/security-analytics-dashboards-plugin#489]
**What is the bug?**
1. The `1_detectors.spec.js` -> `...basic details can be edited` test occasionally fails due to an error when editing the detector name. Sometimes cypress begins typing in the new name before the page finishes loading. Then, once the page load completes, the old detector name replaces the edited value in the detector name field. This hasn't been observed in other fields, but could be possible if unlikely considering the time it takes for cypress to finish typing the detector name. This failure has been observed in `OpenSearch 2.5`, and only when the tests are executed by the [functional test repo](https://github.com/opensearch-project/opensearch-dashboards-functional-test/tree/main/cypress/integration/plugins/security-dashboards-plugin).

1. Cypress hooks can fail to detect API calls, and to find some components when the tests are executed by the functional test repo. 
   1. In this screenshot, cypress fails to find the alert table component despite it being present in the UI.
![Screenshot 2023-03-20 at 11 08 57 AM](https://user-images.githubusercontent.com/79280347/226435978-ea237ffa-4d18-4020-a553-7198bf2fa924.png)
   1. In these screenshots, cypress fails to find the findings details button despite it being present in the UI.
![Screenshot 2023-03-20 at 11 10 31 AM](https://user-images.githubusercontent.com/79280347/226436398-686a2391-5b96-4ef4-a5ba-0ffa605661c8.png)
![Screenshot 2023-03-20 at 11 10 50 AM](https://user-images.githubusercontent.com/79280347/226436405-578a548b-c56e-4147-bbf1-fd3f28a84f78.png)
   1. In this screen shot, cypress fails to detect a call to the `getFindings` API.
![Screenshot 2023-03-20 at 11 45 11 AM](https://user-images.githubusercontent.com/79280347/226436900-2966cb6b-5edc-4cea-b3cf-0eff2ca29494.png)

**Do you have any additional context?**
Issue https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/381 can be considered related as it involves adding tests to the functional test repo. We'll want to consider the cypress hook failures when implementing/refactoring tests in the functional test repo in the future.

**Comment by AWSHurneyt** [comment]
Came across another example of `1_detectors.spec.js` -> `basic details can be edited` being flaky on `main`.
```
Detectors
       ...basic details can be edited:
     CypressError: Timed out retrying after 30050ms: `cy.click()` failed because this element is detached from the DOM.

`<span class="euiComboBoxOption__content">cypress...</span>`
```
https://github.com/opensearch-project/security-analytics-dashboards-plugin/actions/runs/5261336043/jobs/9509332910

The test succeeded upon retry.
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/629/checks

**Comment by amsiglan** [comment]
Flaky tests addressed as part of below PRs:
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/709
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/708
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/589
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/622
