### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by paasi6666** [opensearch-project/security-analytics-dashboards-plugin#582]
**What is the bug?**
When defining a new detector and selecting the "System Logs" type, the "Configure field mapping" are empty.

**How can one reproduce the bug?**
1. Go to Security Analytics>Detectors>Create detector
2. Select any index
3. Click on 'System logs':

![image](https://github.com/opensearch-project/security-analytics-dashboards-plugin/assets/26493612/6cac73d1-3cfe-42a4-88c6-7a64781e8748)

5. See that 'Configure field mapping' is empty

**What is the expected behavior?**
Like the other types (Azure logs for example):
![image](https://github.com/opensearch-project/security-analytics-dashboards-plugin/assets/26493612/af2e09e5-0bc4-46e5-a54c-b3f7c38dbdeb)

**What is your host/environment?**
- OS: Centos7
- Opensearch Version: 2.7.0
- Opensearch-Dashboards Version: 2.7.0

**Comment by paasi6666** [comment]
Bug appears to be in opensearch-project/security-analytics repository.
Will reopen in other repository.

**Comment by sbcd90** [comment]
looking into the issue in opensearch-project/security-analytics repository. closing this.
