### ISSUE TITLE
[BUG] Critical | Submitting the rule without condition breaks the app.

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#615]
**What is the bug?**
Submitting the rule without condition brakes the app.

**How can one reproduce the bug?**
1. Go to the detection rules
2. Click on Create detection rule
3. Fill all the fields except the condition field
4. Submit the form
5. Notice the toaster "No living connection"

**What is the expected behavior?**
The user should not be able to submit the form without the condition field filled in.

**Notes**
The similar happens if tag fields are not in the correct format, different message in screenshot two.

**Do you have any screenshots?**
![Screenshot from 2023-05-31 16-43-48](https://github.com/opensearch-project/security-analytics-dashboards-plugin/assets/28289071/4bcbcc63-625e-46eb-8cae-bf140f270ca7)
![Screenshot from 2023-05-31 16-51-08](https://github.com/opensearch-project/security-analytics-dashboards-plugin/assets/28289071/cd1f0e1f-65bc-44de-8a5e-74fb939682f3)

**Do you have any additional context?**
Request:
`{"id":"25b9c01c-350d-4b95-bed1-836d04a4f324","category":"dns","title":"My Custom Rule","description":"Add some text here","status":"experimental","author":"jovan cvetkovic, pera peric","references":[{"value":""}],"tags":[{"value":""}],"log_source":"","detection":"condition: ''\nSelection_1:\n  Field_1|contains:\n    - Tester\n","level":"critical","false_positives":[{"value":""}]}`

**Comment by amsiglan** [comment]
Fixed
