### ISSUE TITLE
[BUG] Import rule functionality of Security Analytics not working

### ISSUE THREAD

**Issue by jinalp-crest** [opensearch-project/security-analytics-dashboards-plugin#775]
**What is the bug?**
Import rule functionality of Security Analytics not working properly.

**How can one reproduce the bug?**
1. Go to the 'Security Analytics' plugin's rule section under the OpenSearch dashboard.
2. Click on 'Import rule'.
3. Select or drag yml file containing Sigma rules from the local file system.
4. See the error ``Error: Only yaml files are accepted``

**What is the expected behavior?**
Import rule functionality should accept yaml (.yml extension) files including rule fields and detection queries.

**What is your host/environment?**
 - OS: Windows
 - Version: OpenSearch 2.6x
 - Plugins: Security Analytics Plugin (SAP)

**Do you have any screenshots?**
![Screenshot (243)](https://user-images.githubusercontent.com/129835536/230545771-d912e171-b714-4bcc-bef7-4b5fd6e47985.png)

**Comment by amsiglan** [comment]
@jinalp-crest Any update on this one?
