### ISSUE TITLE
[BUG] Create/Import rule | Detection field not validated

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#79]
**What is the bug?**
Users can create/import a rule without validating detection field content

**How can one reproduce the bug?**
1. Go to the Rules page
2. Click on "Import rule" or "Create new rule"
3. Scroll down to the Detection field
4. Enter any invalid YAML content
5. Fill in all required field
6. Click on Create button
7. There is no warning that the Detection field is invalid and Rule can be created

**What is the expected behavior?**
There should be a warning saying the Detection field is invalid and the Rule should not be created

**What is your host/environment?**
- OS: Ubuntu 
- Version 22.10

**Comment by amsiglan** [comment]
Fixed as part of [PR](https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/86)

**Comment by jovancacvetkovic** [comment]
Closing as already fixed with [PR](https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/86)
