### ISSUE TITLE
[BUG] Breadcrumbs navigation is missing a part of the route

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/security-analytics-dashboards-plugin#81]
**What is the bug?**
Breadcrumbs navigation is missing a part of the route and isn't matched with the Sidebar navigation.

**How can one reproduce the bug?**
1. Go to **Security Analytics**
2. Click on the **Rules** [ note the route being: Security Analytics -> Rules ]
3. Click on the **Import rule** button [ note the route being: Security Analytics -> Import rule ]
4. Click on the **Security Analytics** in the Breadcrumbs navigation
5. Overview board is visible

**What is the expected behavior?**
3. The breadcrumbs route should be: Security Analytics -> Rules -> Import rule 
4. The Sidebar navigation displays the **Overview** board, but the navigation sidebar shows **Rules** as current route

**What is your host/environment?**
- OS: Ubuntu
- Version 22.10

**Do you have any screenshots?**
![OpenSearch Dashboards Overview](https://user-images.githubusercontent.com/28289071/200342938-2dcb2862-1ebe-41d3-8182-b68707f40869.png)
![OpenSearch Dashboards Import Rule](https://user-images.githubusercontent.com/28289071/200342962-14d4ee49-930a-4217-ba09-d0e0d56b26c4.png)

**Do you have any additional context?**
Index Management plugin navigation is used as a reference.

**Comment by amsiglan** [comment]
This was fixed as part of [this PR](https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/71)
