### ISSUE TITLE
[BUG] security analytics is breaking the latest build of OSD

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/security-analytics-dashboards-plugin#873]
**What is the bug?**
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/865, this PR introduces a import of `../../types` but the file does not exist.

**How can one reproduce the bug?**
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7808647026/job/21342489996?pr=1025

**What is the expected behavior?**
The OSD tar should be able to run.

**What is your host/environment?**
- Plugins

**Do you have any screenshots?**
<img width="1334" alt="image" src="https://github.com/opensearch-project/security-analytics-dashboards-plugin/assets/13493605/c43140ca-b349-4e1f-b431-916f7325f97f">

**Do you have any additional context?**
Add any other context about the problem.

**Comment by kavilla** [comment]
fixed by: https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/875
