### ISSUE TITLE
[BUG] All notification channels not shown in the dropdown when setting up detector

### ISSUE THREAD

**Issue by amsiglan** [opensearch-project/security-analytics-dashboards-plugin#903]
**What is the bug?**
Microsoft teams channel is not shown in the notification channel list when setting up alerts in the detector creation flow.

**How can one reproduce the bug?**
1. Create channel for MS teams in the notifications plugin
2. Switch to security analytics plugin
3. Open create detector page and fill the basic details
4. Go to the notifications section on page two and try selecting the channel created in step 1 but it is not present in the options list

**What is the expected behavior?**
Show MS teams channel in the list of channels

**What is your host/environment?**
- all OS versions up to 2.12

**Comment by praveensameneni** [comment]
Closing per the above PR
