### ISSUE TITLE
[BUG] "Import rule" rejects both valid .yml and .yaml files on Windows

### ISSUE THREAD

**Issue by zu3st** [opensearch-project/security-analytics-dashboards-plugin#941]
**What is the bug?**
The "Import rule" features fails to accept valid sigma rules on Windows 10, reporting "Error: Only yaml files are accepted" instead.
The detection relies on file.type being one of the supported values defined in `yamlMediaTypes`
https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/1e4b46fed51b79f4509f90a80a77ee314b44865a/public/pages/Rules/utils/constants.ts#L62
https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/1e4b46fed51b79f4509f90a80a77ee314b44865a/public/pages/Rules/containers/ImportRule/ImportRule.tsx#L32

On Windows, the file type set by the FileAPI is controlled by the registry key `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.yml` in both Edge, Chrome and Firefox. Since this key doesn't exist in default installations, an empty string is set, breaking the functionality in all major browsers.

**How can one reproduce the bug?**
1. Go to '/app/opensearch_security_analytics_dashboards#/import-rule' on Windows
2. Drag any valid .yaml or .yml sigma rule onto the drop zone.
4. See error "Error: Only yaml files are accepted" 

**What is the expected behavior?**
Valid sigma rules should be accepted.

**What is your host/environment?**
- OS: Both Windows 10 Enterprise Evaluation 22H2 and Windows 11 Pro 23H2
- Browsers tested: Brave v1.63.174, Edge v122.0.2365.80, Chrome v122.0.6261.129, Firefox 123.0.1

**Do you have any additional context?**
The faulty behaviour was already described in #775 and #844. 
#909 made an attempt to fix the issue by adding additional mime types.
However, we shouldn't rely on a non empty type being present at all:
> User agents must return the [type](https://w3c.github.io/FileAPI/#dfn-type) as an ASCII-encoded string in lower case, such that when it is converted to a corresponding byte sequence, it is a [parsable MIME type](https://mimesniff.spec.whatwg.org/#parsable-mime-type), or the empty string – 0 bytes – if the type cannot be determined.

See https://github.com/react-dropzone/react-dropzone/issues/276#issuecomment-308637324 for related discussion.

**Comment by amsiglan** [comment]
@zu3st Thank you for bringing up this issue with windows. Reading this `we shouldn't rely on a non empty type being present at all`, do you have a proposed solution? Would it make sense to just try parsing file content and check it is valid yaml?

**Comment by zu3st** [comment]
I collected some more results:
| OS | Browser | yaml | yml |
|-|-|-|-|
| MacOS 14.4| Firefox 123.0.1 | application/x-yaml | application/x-yaml |
| MacOS 14.4| Brave 1.63.174 | application/x-yaml | application/x-yaml |
| MacOS 14.4| Safari 17.4 | application/x-yaml | application/x-yaml |
| Debian  (Kali) | Chromium 121 | application/yaml | application/yaml | 
| Debian  (Kali)| Firefox 115.8.0esr | application/yaml | application/yaml | 

with Debian being the only OS tested providing the proper, non deprecated mime-type (which is coincidentally missing in OpenSearch's implementation as well), according to [RFC 9512](https://www.rfc-editor.org/rfc/rfc9512.html#name-media-type-application-yaml).

> Reading this `we shouldn't rely on a non empty type being present at all`, do you have a proposed solution? Would it make sense to just try parsing file content and check it is valid yaml?

While adding `""` and `"application/yaml"` would fix the issue for all browsers tested, mime types don't give us any guarantees.
Since the actual parsing already implements error handling, skipping the mime checks all together does indeed sound like a more resilient approach.

https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/5cd0c8b2f739d463a8f5e81f30403d565120e201/public/pages/Rules/containers/ImportRule/ImportRule.tsx#L45-L49
